
steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'install']

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      TAG=$(date +%Y%m%d-%H%M%S)-$SHORT_SHA
      echo "TAG_NAME=$TAG" > /workspace/tag.sh

- name: 'gcr.io/cloud-builders/docker'
  env:
    - '. /workspace/tag.sh'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/my-first-gcp-instance-323404/a18092024a/validation-service-image:$TAG_NAME', '.']

- name: 'gcr.io/cloud-builders/docker'
  env:
    - '. /workspace/tag.sh'
  args: ['push', 'us-central1-docker.pkg.dev/my-first-gcp-instance-323404/a18092024a/validation-service-image:$TAG_NAME']

- name: 'bash'
  env:
    - '. /workspace/tag.sh'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pwd
      K8S_IMAGE="us-central1-docker.pkg.dev/my-first-gcp-instance-323404/a18092024a/validation-service-image:$TAG_NAME"
      sed -i 's|LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE|'"$K8S_IMAGE"'|' deployment.yaml

- name: 'gcr.io/cloud-builders/kubectl'
  env:
    - '. /workspace/tag.sh'
  args: ['apply', '-f', 'persistentvolume.yaml']
  env: 
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gke-test-1'
    - 'CLOUDSDK_CORE_PROJECT=my-first-gcp-instance-323404'

- name: 'gcr.io/cloud-builders/kubectl'
  env:
    - '. /workspace/tag.sh'
  args: ['apply', '-f', 'deployment.yaml']
  env: 
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gke-test-1'
    - 'CLOUDSDK_CORE_PROJECT=my-first-gcp-instance-323404'

images:
- 'us-central1-docker.pkg.dev/my-first-gcp-instance-323404/a18092024a/validation-service-image:$TAG_NAME'

options:
  logging: 'CLOUD_LOGGING_ONLY'



# us-central1-docker.pkg.dev/my-first-gcp-instance-323404/a18092024a