apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: flask-deployment  
spec:  
  replicas: 3  
  selector:  
    matchLabels:  
      app: flask  
  template:  
    metadata:  
      labels:  
        app: flask  
    spec:  
      containers:  
      - name: flask  
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE
        ports:  
        - containerPort: 8080


